local M = {}
local colors = require("miracle-of-god.utils.color").COLORS

local function HL(syntaxName, options)
	vim.api.nvim_set_hl(0, syntaxName, options)
end

function M.setHighLight()
	-- basic
	HL("Normal", { fg = colors.FG, bg = colors.BG })
	HL("Comment", { fg = colors.GRAY, italic = true })
	HL("CursorLine", { bg = "" })
	HL("CursorColumn", { bg = "" })
	HL("LineNr", { fg = colors.GRAY })
	HL("CursorLineNr", { fg = colors.RED })
	HL("String", { fg = colors.RED })
	HL("Number", { fg = colors.BROWN })
	HL("Boolean", { fg = colors.GREEN })
	HL("Function", { fg = colors.BLUE })
	HL("Keyword", { fg = colors.PINK })
	HL("Operator", { fg = colors.ORANGE })
	HL("Type", { fg = colors.GREEN })
	HL("Identifier", { fg = colors.PURPLE })
	HL("PreProc", { fg = colors.PINK })
	HL("Special", { fg = colors.ORANGE })
	HL("Underlined", { fg = colors.GREEN, underline = true })
	HL("Constant", { fg = colors.BLUE })
	HL("Label", { fg = colors.BLUE })
	HL("SpecialKey", { fg = colors.ORANGE })
	HL("Title", { fg = colors.BLUE })
	HL("Tag", { fg = colors.PURPLE })
	HL("@variable", { fg = colors.ORAK, italic = true })
	HL("Search", { fg = colors.BG, bg = colors.YELLOW })
	HL("IncSearch", { fg = colors.BG, bg = colors.YELLOW })
	HL("DiagnosticError", { fg = colors.RED })
	HL("DiagnosticWarn", { fg = colors.YELLOW })
	HL("DiagnosticInfo", { fg = colors.BLUE })
	HL("DiagnosticHint", { fg = colors.ORANGE })
	HL("Directory", { fg = colors.BLUE })
	HL("NotifyERRORBorder", { fg = colors.RED })
	HL("NotifyERRORTitle", { fg = colors.RED })
	HL("NotifyERRORBody", { fg = colors.RED })
	HL("NotifyERRORIcon", { fg = colors.RED })
	HL("NotifyWARNBorder", { fg = colors.YELLOW })
	HL("NotifyWARNTitle", { fg = colors.YELLOW })
	HL("NotifyWARNBody", { fg = colors.YELLOW })
	HL("NotifyWARNIcon", { fg = colors.YELLOW })
	HL("NotifyINFOBorder", { fg = colors.BLUE })
	HL("NotifyINFOTitle", { fg = colors.BLUE })
	HL("NotifyINFOBody", { fg = colors.BLUE })
	HL("NotifyINFOIcon", { fg = colors.BLUE })
	HL("markdownH1", { fg = colors.RED, bold = true })
	HL("markdownH2", { fg = colors.ORANGE, bold = true })
	HL("markdownH3", { fg = colors.YELLOW, bold = true })
	HL("markdownH4", { fg = colors.GREEN, bold = true })
	HL("markdownH5", { fg = colors.PINK, bold = true })
	HL("markdownH6", { fg = colors.PURPLE, bold = true })
	HL("DiffAdd", { fg = colors.GREEN })
	HL("DiffChange", { fg = colors.BROWN })
	HL("DiffDelete", { fg = colors.RED })
end

return M
